theme: jekyll-theme-cayman
plugins:
  - jekyll-commonmark
markdown: GFM
theme: jekyll-theme-cayman
plugins:
  - jekyll-commonmark
  - jekyll-relative-links

markdown: GFM
relative_links:
  enabled: true
  collections: true
